name: build
on:
  - push
  - pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Prettier
        run: |
          npx prettier --check .
      - name: Typecheck
        run: |
          npx tsc --noEmit
      - name: Test
        run: |
          make test
      - name: Pack
        run: |
          make sdist
      - uses: actions/upload-artifact@v2
        with:
          path: xstream-tuplewise-*.tgz
